# The source file.
default[:cas][:war][:source] = "http://download.nubic.northwestern.edu/nubic_cas/nubic-cas-server-webapp-3.4.3.NUBIC-002.war"
default[:cas][:war][:checksum] = "ede527851672abbfdf00cf80635c81c7bfb4bb3729733c26eae9ee116bd6a8d0"

# CAS server configuration.
# Note: don't set a database password here; a password is generated by the
# database recipe.
default[:cas][:dir] = "/etc/nubic/cas-server"
default[:cas][:bcsec] = "#{node[:cas][:dir]}/bcsec.rb"
default[:cas][:log] = "/var/log/cas/nubic-cas.log"

# Note: This isn't derived from cas[:dir] because the properties file MUST be
# present at this location to take effect.
default[:cas][:properties] = "/etc/nubic/cas-server/cas.properties"

# This path MUST NOT be prefixed with /, as it's also used to derive WAR
# filenames.
default[:cas][:public_path] = "cas"

# Database configuration.
default[:cas][:database][:name] = "nubic_cas"
default[:cas][:database][:user] = "nubic_cas"
default[:cas][:database][:bcdatabase][:group] = "local_postgresql"
