maintainer       "Northwestern University"
maintainer_email "yipdw@northwestern.edu"
license          "Apache 2.0"
description      "Installs/Configures cas"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.0.0"

depends "aker"
depends "apache2"
depends "bcdatabase"
depends "database"
depends "monit"
depends "openssl"
depends "ssl_certificates"
depends "application_user"
depends "tomcat"
