maintainer       "Northwestern University"
maintainer_email "yipdw@northwestern.edu"
license          "Apache 2.0"
description      "NCS Navigator deployment"
long_description IO.read(File.join(File.dirname(__FILE__), 'README'))
version          "2.0.0"

depends "aker"
depends "apache2"
depends "application_user"
depends "bcdatabase"
depends "database"
depends "postgresql"
depends "ssl_certificates"
depends "tomcat"
depends "monit"
depends "logrotate"
depends "rvm"

attribute 'ncs_navigator/env',
  :display_name => 'Environment',
  :description => 'Application environment',
  :required => 'required'

attribute 'ncs_navigator/cas/base_url',
  :display_name => 'CAS base URL',
  :required => 'required'

attribute 'ncs_navigator/cas/proxy_callback_url',
  :display_name => 'CAS proxy callback URL',
  :required => 'required'

attribute 'ncs_navigator/cas/proxy_retrieval_url',
  :display_name => 'CAS proxy retrieval URL',
  :required => 'required'

attribute 'ncs_navigator/db/admin/user',
  :display_name => 'DB admin user',
  :description => 'The database user that will set up new Cases, Ops, and PSC databases',
  :default => 'ncs_navigator_db_admin'

attribute 'ncs_navigator/db/admin/password',
  :display_name => 'DB admin password',
  :description => 'The password for the DB admin user',
  :required => 'required'

attribute 'ncs_navigator/db/host',
  :display_name => 'DB host',
  :description => 'The hostname of the database node',
  :required => 'required'

attribute 'ncs_navigator/cases/session_secret/path',
  :display_name => 'Session secret path',
  :description => %q{
  A path on the filesystem where Cases' session secret will be generated and
  stored.  This is used by Chef recipes to record generation of the session
  secret and propagate it to other places where it's needed.  The session
  secret may be regenerated by deleting this file.
  },
  :default => '/etc/nubic/ncs/.chef-state/cases_session_secret'

attribute 'ncs_navigator/cases/session_secret/env_var',
  :display_name => 'Environment variable for session secret',
  :description => %q{Name of an environment variable that will contain Cases' session secret},
  :default => 'CORE_SECRET'

attribute 'ncs_navigator/cases/mail_from',
  :display_name => 'Cases mail address',
  :description => 'Email address to use for Cases-sent mail',
  :required => 'required'

attribute 'ncs_navigator/cases/sync_log_level',
  :display_name => 'Sync log level',
  :default => 'DEBUG'

attribute 'ncs_navigator/cases/app/root',
  :display_name => 'Cases root directory',
  :default => '/var/www/apps/ncs_navigator_cases'

attribute 'ncs_navigator/cases/app/min_instances',
  :display_name => 'Minimum number of Cases workers',
  :default => '5'

attribute 'ncs_navigator/cases/app/url',
  :display_name => 'Root URL for Cases',
  :required => 'required'

attribute 'ncs_navigator/cases/with_specimens',
  :display_name => 'Collect specimens',
  :default => 'false'

attribute 'ncs_navigator/cas/machine_accounts/file',
  :display_name => 'Machine accounts file on the CAS server',
  :default => '/etc/nubic/ncs/machine_accounts.yml'

attribute 'ncs_navigator/cas/machine_accounts/data',
  :description => 'Aggregation of all machine accounts known to the CAS server',
  :required => 'required'

attribute 'ncs_navigator/cases/machine_account/username',
  :required => 'required'

attribute 'ncs_navigator/cases/machine_account/password',
  :required => 'required'

attribute 'ncs_navigator/cases/db/name_prefix',
  :display_name => 'Database name prefix',
  :default => 'ncs_navigator_cases'

attribute 'ncs_navigator/cases/db/user_prefix',
  :display_name => 'Database user prefix',
  :default => 'ncs_navigator_cases'

attribute 'ncs_navigator/cases/db/bcdatabase/group',
  :display_name => 'Bcdatabase group name',
  :required => 'required'

attribute 'ncs_navigator/cases/db/bcdatabase/config',
  :display_name => 'Bcdatabase configuration name',
  :default => 'ncs_navigator_core'

attribute 'ncs_navigator/cases/db/pool_size',
  :display_name => 'Database connection pool size',
  :default => '10'

attribute 'ncs_navigator/ini/path',
  :display_name => 'NCS Navigator INI path',
  :default => '/etc/nubic/ncs/navigator.ini'

attribute 'ncs_navigator/cases/db/password',
  :display_name => 'DB password',
  :required => 'required'

attribute 'ncs_navigator/cases/status_endpoint',
  :display_name => 'Status service endpoint',
  :default => '/api/v1/system-status'

attribute 'ncs_navigator/cases/worker/pid',
  :display_name => 'Worker PID path',
  :default => '/var/www/apps/ncs_navigator_cases/shared/pids/sidekiq.pid'

attribute 'ncs_navigator/cases/worker/log',
  :display_name => 'Worker log path',
  :default => '/var/www/apps/ncs_navigator_cases/shared/log/sidekiq.log'

attribute 'ncs_navigator/cases/worker/concurrency',
  :display_name => 'Number of worker threads',
  :default => '5'

attribute 'ncs_navigator/cases/scheduler/pid',
  :display_name => 'Scheduler PID path',
  :default => '/var/www/apps/ncs_navigator/shared/pids/scheduler.pid'

attribute 'ncs_navigator/cases/scheduler/log',
  :display_name => 'Scheduler log path',
  :default => '/var/www/apps/ncs_navigator/shared/log/scheduler.log'

attribute 'ncs_navigator/cases/ssl/certificate',
  :display_name => 'Cases SSL certificate',
  :description => 'Filename of an SSL certificate for Cases',
  :default => '/etc/pki/tls/certs/cases.crt'

attribute 'ncs_navigator/cases/ssl/certificate_chain',
  :display_name => 'Cases SSL certificate chain',
  :description => 'Filename of an SSL certificate chain presented by Cases'

attribute 'ncs_navigator/cases/ssl/key',
  :display_name => 'Cases SSL key',
  :description => 'Filename of an SSL private key for Cases',
  :default => '/etc/pki/tls/private/cases.key'

attribute 'ncs_navigator/cases/user/name',
  :display_name => 'Cases user',
  :description => 'The user that will run Cases',
  :default => 'ncs_navigator_cases'

attribute 'ncs_navigator/cases/user/groups',
  :display_name => 'Cases user groups',
  :description => 'Additional groups for the Cases application user',
  :type => 'array',
  :default => []

attribute 'ncs_navigator/cases/user/ssh_keys',
  :display_name => 'Cases SSH keys',
  :description => 'SSH keys that can be used with the Cases user',
  :type => 'array',
  :default => []

attribute 'ncs_navigator/cases/study_center/sc_id',
  :display_name => 'Cases study center ID',
  :description => 'The ID of the study center serviced by the Cases instance',
  :required => 'required'

attribute 'ncs_navigator/cases/study_center/recruitment_type_id',
  :required => 'required'

attribute 'ncs_navigator/instruments/dir',
  :default => '/var/www/apps/ncs_instruments'

attribute 'ncs_navigator/hosted_data/dir',
  :default => '/var/www/apps/ncs_navigator_hosted_data'

attribute 'ncs_navigator/cases/study_center/short_name',
  :display_name => 'Cases study center short name',
  :description => 'An abbreviation for the study center serviced by the Cases instance',
  :required => 'required'

attribute 'ncs_navigator/cases/study_center/sampling_units/data_bag',
  :display_name => 'Sampling units data bag',
  :description => 'The data bag to use for sampling units data',
  :default => 'ncs_ssus'

attribute 'ncs_navigator/cases/study_center/sampling_units/data_bag_item',
  :display_name => 'Sampling units data bag item',
  :description => 'The item in the sampling units data bag to use',
  :required => 'required'

attribute 'ncs_navigator/cases/study_center/sampling_units/target',
  :display_name => 'Sampling units file',
  :description => 'Where the sampling units data will be written',
  :default => '/etc/nubic/ncs/ssu_tsus.csv'

attribute 'ncs_navigator/cases/study_center/footer_logo_left/path',
  :display_name => 'Left footer logo path',
  :default => '/var/www/apps/ncs_shared/footer_logo_left.png',
  :required => 'required'

attribute 'ncs_navigator/cases/study_center/footer_logo_left/source',
  :display_name => 'Left footer logo source',
  :default => 'https://github.com/NUBIC/ncs_navigator_deployment/raw/51d699dd797fc0deb3371af25f5c49b9dce6a38b/logos/footer_left.png',
  :required => 'recommended'

attribute 'ncs_navigator/cases/study_center/footer_logo_left/checksum',
  :display_name => 'Left footer logo checksum',
  :default => '2d288345f95e90c25a59068b6eab776c82ff6c555a80d41322ba203bccc9d524',
  :required => 'recommended'

attribute 'ncs_navigator/cases/study_center/footer_logo_right/path',
  :display_name => 'Right footer logo path',
  :default => '/var/www/apps/ncs_shared/footer_logo_right.png',
  :required => 'required'

attribute 'ncs_navigator/cases/study_center/footer_logo_right/source',
  :display_name => 'Right footer logo source',
  :default => 'https://github.com/NUBIC/ncs_navigator_deployment/raw/51d699dd797fc0deb3371af25f5c49b9dce6a38b/logos/footer_right.png',
  :required => 'recommended'

attribute 'ncs_navigator/cases/study_center/footer_logo_right/checksum',
  :display_name => 'Right footer logo checksum',
  :default => '7583e308a380440b4cd47c0fcb7599113d81e499ccb78f50e303eaf34e8c5d2f',
  :required => 'recommended'

attribute 'ncs_navigator/cases/study_center/exception_email_recipients',
  :display_name => "Cases exception email recipients",
  :default => [],
  :required => 'required'

attribute 'ncs_navigator/cases/study_center/footer_text',
  :display_name => 'Footer text',
  :default => '',
  :required => 'recommended'

attribute 'ncs_navigator/cases/study_center/username',
  :display_name => 'Study center username type',
  :default => 'NetID'

attribute 'ncs_navigator/psc/url',
  :required => 'required'

attribute 'ncs_navigator/psc/db/name',
  :default => 'psc'

attribute 'ncs_navigator/psc/db/password',
  :required => 'required'

attribute 'ncs_navigator/psc/ssl/ca_file',
  :default => '/etc/pki/tls/certs/psc_ca.crt'

attribute 'ncs_navigator/smtp/authentication',
  :required => 'required'

attribute 'ncs_navigator/smtp/host',
  :default => 'localhost'

attribute 'ncs_navigator/smtp/port',
  :default => '25'

attribute 'ncs_navigator/smtp/starttls',
  :default => 'false'

attribute 'ncs_navigator/smtp/username',
  :required => 'required'

attribute 'ncs_navigator/smtp/password',
  :required => 'required'

attribute 'ncs_navigator/staff_portal/bootstrap_user',
  :required => 'required'

attribute 'ncs_navigator/staff_portal/email_reminder',
  :default => 'false'

attribute 'ncs_navigator/staff_portal/exception_recipients',
  :required => 'required',
  :default => []

attribute 'ncs_navigator/staff_portal/google_analytics_number',
  :required => 'optional'

attribute 'ncs_navigator/staff_portal/mail_from',
  :required => 'required'

attribute 'ncs_navigator/staff_portal/psc_user_password',
  :required => 'required'

attribute 'ncs_navigator/staff_portal/url',
  :required => 'required'

%w(
  mdes_warehouse_working
  mdes_warehouse_reporting
  mdes_import_working
  mdes_import_reporting
).each do |db|
  attribute "ncs_navigator/warehouse/db/databases/#{db}/name_prefix",
    :default => db

  attribute "ncs_navigator/warehouse/db/databases/#{db}/bcdatabase/config",
    :default => db

  attribute "ncs_navigator/warehouse/db/databases/#{db}/bcdatabase/group",
    :required => 'required'
end

attribute "ncs_navigator/warehouse/db/user_prefix",
  :default => 'ncs_mdes_warehouse'

attribute "ncs_navigator/warehouse/db/password",
  :required => 'required'
